FROM ubuntu

ARG UID
ARG AUDIO_GID

ENV PULSE_SERVER=unix:/tmp/pulseaudio.socket
ENV PULSE_COOKIE=/tmp/pulseaudio.cookie

RUN groupmod --gid ${AUDIO_GID} audio && groupadd -g ${UID} usergroup && useradd -m -l -u ${UID} --gid ${UID} --groups audio user
RUN DEBIAN_FRONTEND=noninteractive apt update && apt install -y --no-install-recommends curl gnupg2 pulseaudio ca-certificates
RUN curl -sS https://download.spotify.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb http://repository.spotify.com stable non-free" | tee /etc/apt/sources.list.d/spotify.list
RUN ln -fs /usr/share/zoneinfo/Europe/Lisbon /etc/localtime
RUN DEBIAN_FRONTEND=noninteractive apt update && apt install -y --no-install-recommends spotify-client

COPY pulseaudio.client.conf /etc/pulse/client.conf

CMD ["/usr/bin/spotify"]

